variables:
- name: major
  value: '0'
- name: minor
  value: '1'
- name: extensionName
  value: 'Terraform'
- name: marketplaceServiceConnection
  value: 'marketplaceServiceConnection'
- name: publisherId
  value: 'ms-devlabs'
- name: publicExtensionName
  value: "Terraform"
- name: extensionId
  value: "custom-terraform-tasks"

name: $(major).$(minor)$(rev:.r)

trigger:
  branches:
    include:
    - main

pr: none

resources:
  repositories:
    - repository: pipeline-templates
      type: git
      name: Sage/pipeline-templates
      ref: main

stages:
- stage: 'Build'
  jobs:
  - job: 'BuildPack'
    displayName: "Build and package"
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'
    - template: build.yml@pipeline-templates
    - template: package.yml@pipeline-templates
      parameters:
        extensionName: $(extensionName)
        outputPath: 'out'
        rootPath: './build'

- stage: 'DeployDev'
  displayName: 'Deploy to dev'
  dependsOn: Build
  condition: succeeded()
  jobs: 
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'dev'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      updateTaskVersion: true
      extensionId: $(extensionId)

- stage: 'DeployTest'
  displayName: 'Deploy to Test'
  dependsOn: DeployDev
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'test'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      updateTaskVersion: true
      extensionId: $(extensionId)

- stage: 'DeployRelease'
  displayName: 'Deploy Release'
  dependsOn: DeployTest
  condition: succeeded()
  jobs:
  - template: deploy.yml@pipeline-templates
    parameters:
      environment: 'public'
      extensionName: $(extensionName)
      marketplaceConnectedServiceName: $(marketplaceServiceConnection)
      publisherId: $(publisherId)
      publicExtensionName: $(publicExtensionName)
      extensionVisibility: 'public'
      updateTaskVersion: true
      extensionId: $(extensionId)
